from .colors import (
    BRIGHT_GREEN, DARK_GREEN,
    BRIGHT_YELLOW,
    BRIGHT_GRAY, DARK_GRAY)

from .label_positions import LOWER_RIGHT


settings = {
    # node style
    'NODE_TRANSPARENCY': 255,
    'NODE_SIZE': 25,
    'NODE_BORDER_WIDTH': 4,
    'NODE_BORDER_PAINT': BRIGHT_GREEN,
    'NODE_FILL_COLOR': DARK_GREEN,
    'NODE_SELECTED_PAINT': BRIGHT_YELLOW,

    # node label style
    'NODE_LABEL_COLOR': BRIGHT_GRAY,
    'NODE_LABEL_FONT_SIZE': 16,
    'NODE_LABEL_POSITION': LOWER_RIGHT,

    # edge style
    'EDGE_TRANSPARENCY': 255,
    'EDGE_WIDTH': 2.5,
    'EDGE_LINE_TYPE': 'SOLID',
    'EDGE_STROKE_SELECTED_PAINT': BRIGHT_YELLOW,
    'EDGE_STROKE_UNSELECTED_PAINT': BRIGHT_GRAY,
    'EDGE_TARGET_ARROW_UNSELECTED_PAINT': BRIGHT_GRAY,
    'EDGE_TARGET_ARROW_SHAPE': 'DELTA',

    # network style
    'NETWORK_BACKGROUND_PAINT': DARK_GRAY
}
